---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tk-test
  annotations:
    github.com/project-slug: tarandeepkaur28/tk-test
spec:
  type: service
  owner: tarandeep
  lifecycle: unknown
